### ISSUE TITLE
Failed to set 2DNavGoal

### ISSUE THREAD

**Issue by WysokiStudent** [ros-noetic-arch/ros-noetic-turtlebot3-navigation#1]
Setting a 2DNavGoal in Rviz has no effect on a simulated turtlebot.

Running `roslaunch turtlebot3_navigation turtlebot3_navigation.launch` results in rviz starting but the following error is displayed in the terminal:

`Failed to create the dwa_local_planner/DWAPlannerROS planner, are you sure it is properly registered and that the containing library is built? Exception: According to the loaded plugin descriptions the class dwa_local_planner/DWAPlannerROS with base class type nav_core::BaseLocalPlanner does not exist. Declared types are  base_local_planner/TrajectoryPlannerROS`

The solution proposed on the forums is to install dwa-local-planner but this package is not available in the AUR for noetic, is this an accidental omission or is it purposeful?

Link to forum: https://answers.ros.org/question/266411/navigation-problem-with-cob3-dwaplanerros-create-fail/

Edit:
I just realized I posted this in the wrong repository - sorry.

**Comment by acxz** [comment]
> The solution proposed on the forums is to install dwa-local-planner but this package is not available in the AUR for noetic, is this an accidental omission or is it purposeful?

Probably not an accidental omission, most likely the package has been updated and the PKGBUILD/dependencies have not been reflected on the AUR.

**Comment by WysokiStudent** [comment]
To be honest it looks like dwa-local-planner is an empty repository, I'm not sure if it was ever updated.
 https://github.com/ros-noetic-arch/ros-noetic-dwa-local-planner

**Comment by acxz** [comment]
Weird seems like it was created but never filled out, there is a melodic version for it as well. I'm guessing there was a hiccup during the transfer from melodic to noetic. Thx for looking closer at it, i'll upload the dwa-local-planner package soon.

**Comment by acxz** [comment]
kk I just filled out that PKGBUILD. can you try to reproduce the error again and if it has been resolved close it? Thx

**Comment by WysokiStudent** [comment]
Installing the said package did fix the problem, thanks a ton for maintaining the ROS middleware so actively.
